Consume user gesture in `element.requestFullscreen()`
whatwg/fullscreen pull request #153
Opened 2019-05-28 12:54 UTC by foolip

Depends on https://github.com/whatwg/html/pull/3851.

Fixes https://github.com/whatwg/fullscreen/issues/152.

2019-05-28 13:42 UTC, mustaqahmed commented
Thanks, this looks good from user activation perspective.

2019-05-29 18:53 UTC, SummerLW commented
https://github.com/web-platform-tests/wpt/pull/16758 has been merged into wpt repository.
Three new tests about this behavior are now in https://w3c-test.org/fullscreen/api/
element-request-fullscreen-twice-manual.tentative.html
element-request-fullscreen-two-elements-manual.tentative.html
element-request-fullscreen-two-iframes-manual.tentative.html

2019-12-10 16:13 UTC, mustaqahmed commented on fullscreen.bs
> + <li><p>If <var>error</var> is false, then <a>consume user activation</a> for
FYI: This should now point to the newly added definition of [consumption](https://html.spec.whatwg.org/multipage/interaction.html#consume-user-activation).  Not sure why the PR preview doesn't show a link.

2022-05-18 16:22 UTC, mustaqahmed commented on fullscreen.bs
> + <li><p>If <var>error</var> is false, then <a>consume user activation</a> for
Looks like the preview is correctly pointing to the HTML spec link now.

2022-05-18 16:42 UTC, mustaqahmed reviewed
I wanted to approve this PR, but apparently I don't have permission to do that!  @domenic?

2022-05-18 16:43 UTC, domenic requested changes

2022-05-18 16:43 UTC, domenic commented on fullscreen.bs
> + <var>pendingDoc</var>'s <a>browsing context</a>.
This should be pendingDoc's relevant global object, not its browsing context.

2022-11-01 07:55 UTC, domenic commented
@foolip, can we help move this along? I'm happy to rebase it and also take care of any changes after #208.

This would probably solve the issue @marcoscaceres raises in https://github.com/web-platform-tests/wpt/issues/36727 of giving a cross-browser way of consuming user activation.

2022-11-01 08:40 UTC, marcoscaceres commented
I guess it depends on what features/API calls follow a call to `.requestFullScreen()`... I see there is mention of Pointerlock in the bug and Screen Orientation Lock is another.  

I'm simultaneously hoping we can prevent the Screen Orientation API (which depends on FS API) from arbitrarily changing the screen orientation [without a user gesture](https://github.com/w3c/screen-orientation/pull/218). 

If you have an Android device handy, try this out in Chrome: 
https://marcoscaceres.github.io/playground/annoying.html 

(if you can't try it out, it loops rapidly changing the screen orientation making it difficult of users to access the browsers UI - you need to either turn off the screen or quickly swipe from the bottom to stop it). 

I personally don't think the above behavior should be acceptable for any API to do on the Web. So, I was hoping we wouldn't consume the user activation in FS API, but rather have the Screen Orientation API consume the user activation. 

Alternatively, we could have it consume the user activation if #186 was in place, all in one go. The advantage being that it wouldn't breaking any sites that are depending on FS API to not consuming the user activation.

For pointerlock, maybe a solution like #186 could also work. You request them all at once, and exiting fulls screen releases all the locks.

2022-11-01 15:52 UTC, EdgarChen commented
Currently, Gecko also consume the user activation as we had received a bug of trapping the user in fullscreen mode, which invites DOS and spoofing possibilities. And for pointer lock, we allow it without a vaild user activation if document is in fullscreen mode.

2022-11-01 20:30 UTC, marcoscaceres commented
Discussing with my WebKit colleagues... but if both Gecko and Chromium consume it, we may follow suit. Let me get back to you. 

> And for pointer lock, we allow it without a vaild user activation if document is in fullscreen mode.

That is contrary to what is in the Pointer Lock spec, right? Why don't we just link the actions together via a mechanism like in #186? 

(also, we should really rewrite the pointer lock spec to integrate properly with the Full Screen API)

2022-11-02 16:00 UTC, mustaqahmed commented
> Currently, Gecko also consume the user activation as we had received a bug of trapping the user in fullscreen mode, which invites DOS and spoofing possibilities.

Chrome originally proposed this consumption behavior to prevent a spoof, see https://crbug.com/851302.

>> And for pointer lock, we allow it without a vaild user activation if document is in fullscreen mode.
>
> That is contrary to what is in the Pointer Lock spec, right? Why don't we just link the actions together via a mechanism like in https://github.com/whatwg/fullscreen/issues/186?

IIRC Chrome added a similar hack to support some compat argument, can't recall any details!  Yes, #186 would be nice.

2022-11-02 16:30 UTC, EdgarChen commented
https://github.com/whatwg/fullscreen/issues/186 sounds reasonable to me.

2022-11-02 21:58 UTC, marcoscaceres commented
@EdgarChen, if we go with something like #207 (new dictionary member), would you be willing to remove the pointerLock workaround in Firefox? That way, we can just have a consistent model across three specs. 

Similar question for Chrome folks. I'm willing to spec that up if everyone is supportive.

2022-11-03 04:36 UTC, domenic commented on fullscreen.bs
> + <var>pendingDoc</var>'s <a>node navigable</a>'s <a>active window</a>.
Use `<a for=navigable>activate window</a>`

2022-11-03 09:35 UTC, EdgarChen commented
> @EdgarChen, if we go with something like #207 (new dictionary member), would you be willing to remove the pointerLock workaround in Firefox?

To clarify this a bit more: This is not a workaround added for consuming user activation, we behave the same all the way back to Firefox 22 at least (before the current user activation model in spec is proposed). I am worried that removing this would cause compatibility problem. :(

2022-11-14 12:07 UTC, foolip commented
@marcoscaceres there are 3 tests in wpt that are tentative due to #152:

https://github.com/web-platform-tests/wpt/blob/master/fullscreen/api/element-request-fullscreen-twice-manual.tentative.html
https://github.com/web-platform-tests/wpt/blob/master/fullscreen/api/element-request-fullscreen-two-elements-manual.tentative.html
https://github.com/web-platform-tests/wpt/blob/master/fullscreen/api/element-request-fullscreen-two-iframes-manual.tentative.html

But I think with consuming, this can be reduced to just the first test, ensuring the second call is rejected.

2022-11-14 12:42 UTC, domenic commented on fullscreen.bs
> + <var>pendingDoc</var>'s <a>node navigable</a>'s <a for=navigable>active window</a>.
Yeah, looks like that's not properly exported. I'll get on it.

2022-11-14 23:03 UTC, marcoscaceres commented
Filed WebKit bug:
https://bugs.webkit.org/show_bug.cgi?id=247920

Thanks for the details about the tests, @foolip. If those can get updated and changed to non-tentative, that would be great.

2022-11-15 12:16 UTC, upsuper commented
I have a feeling that there is nothing wrong to allow `requestFullscreen` without user activation when the document is already in fullscreen, or is entering fullscreen (by a previous call). Though to be honest I'm not sure whether it is useful to allow that either.

2022-11-15 12:51 UTC, foolip commented
@upsuper I think you're right about that, since the page script already has full control over what's being presented and could replace all the contents of the current fullscreen element. However, that'd be a change from the currently implemented behavior, and I'd prefer to handle that separately from this. Can you file an issue if you think we should change that?

2022-11-15 12:52 UTC, foolip commented
@marcoscaceres test PR is up and the whole PR template is filled in now.

2022-11-15 21:14 UTC, marcoscaceres commented
Thanks @foolip! Everything looks great.

2022-11-16 01:38 UTC, domenic commented on fullscreen.bs
> + <var>pendingDoc</var>'s <a>node navigable</a>'s <a for=navigable>active window</a>.
Actually you should just use `<var>pendingDoc</var>'s <a>relevant global object</a>`! No need to go all the way to navigable and back.

2022-11-28 04:00 UTC, marcoscaceres commented on fullscreen.bs
> + <var>pendingDoc</var>'s <a>node navigable</a>'s <a for=navigable>active window</a>.
```suggestion
 <li><p>If <var>error</var> is false, then <a>consume user activation</a> given
 <var>pendingDoc</var>'s <a>relevant global object</a>.
```

2022-12-09 12:25 UTC, marcoscaceres commented
This is now also implemented in WebKit. 

@foolip, anything left to get this merged?

2023-05-03 07:17 UTC, foolip commented on fullscreen.bs
> + <var>pendingDoc</var>'s <a>node navigable</a>'s <a for=navigable>active window</a>.
Ah, thanks!

2023-05-03 07:19 UTC, foolip commented on fullscreen.bs
> + <var>pendingDoc</var>'s <a>node navigable</a>'s <a for=navigable>active window</a>.
Applied, thanks!

2023-05-03 07:24 UTC, foolip commented
@marcoscaceres sorry I totally dropped the ball here. I've updated the PR and all I need now is review from someone with write access. Paging @annevk, as @domenic seems to be OOO today.

2023-05-03 07:27 UTC, annevk approved these changes
This seems fine. The step immediately preceding this could do with some love at some point. The booleans are still hurting me.

2023-05-03 07:32 UTC, foolip commented
Thanks @annevk! Let me try inverting the preceding steps and see if you like that.

2023-05-03 07:57 UTC, merged